measures = {
    # cup
    'C': 'cup',
    'c': 'cup',
    'cup': 'cup',
    'cups': 'cup',

    # teaspoon
    'tsp': 'teaspoon',
    'tsps': 'teaspoon',
    't': 'teaspoon',
    'ts': 'teaspoon',
    'teaspoon': 'teaspoon',
    'teaspoons': 'teaspoon',

    # tablespoon
    'tbsp': 'tablespoon',
    'tbsps': 'tablespoon',
    'T': 'tablespoon',
    'Ts': 'tablespoon',
    'TB': 'tablespoon',
    'TBs': 'tablespoon',
    'TBl': 'tablespoon',
    'TBls': 'tablespoon',
    'TBL': 'tablespoon',
    'TBLs': 'tablespoon',
    'Tbsp': 'tablespoon',
    'Tbsps': 'tablespoon',
    'tablespoon': 'tablespoon',
    'tablespoons': 'tablespoon',
    'Tablespoon': 'tablespoon',
    'Tablespoons': 'tablespoon',

    # gram
    'g': 'gram',
    'gram': 'gram',
    'grams': 'gram',

    # kilogram
    'kg': 'kilogram',
    'kilogram': 'kilogram',
    'kilograms': 'kilogram',

    # liter
    'L': 'liter',
    'l': 'liter',
    'liter': 'liter',
    'liters': 'liter',

    # pound
    'lb': 'pound',
    'lbs': 'pound',
    'pound': 'pound',
    'pounds': 'pounds',

    # milliliter
    'mL': 'milliliter',
    'mLs': 'milliliter',
    'ml': 'milliliter',
    'mls': 'milliliter',

    # ounce
    'oz': 'ounce',
    'ozs': 'ounce',
    'ounce': 'ounce',
    'ounces': 'ounce',

    # quart
    'qt': 'quart',
    'qts': 'quart',
    'quart': 'quart',
    'quarts': 'quart',

    # gallon
    'gal': 'gallon',
    'gals': 'gallon',
    'gallon': 'gallon',
    'gallons': 'gallon',

    # pint
    'pt': 'pint',
    'pts': 'pints',
    'pint': 'pint',
    'pints': 'pint',

    # pinch
    'pinch': 'pinch',
    'pinches': 'pinch',

    # dash
    'dash': 'dash',
    'dashes': 'dash',

    # stick
    'stick': 'stick',
    'sticks': 'stick',

    # packet
    'packet': 'packet',
    'packets': 'packet',

    # package
    'package': 'package',
    'packages': 'package',

    # carton
    'carton': 'carton',
    'cartons': 'carton',

    # can
    'can': 'can',
    'cans': 'can',

    # jar
    'jar': 'jar',
    'jars': 'jar',

    # sprig
    'spring': 'sprig',
    'springs': 'sprig',

    # clove
    'clove': 'clove',
    'cloves': 'clove'
}

ignore_words = [
    'optional'
]

# https://kathytemean.wordpress.com/2009/04/25/101-descriptive-words-for-foods/
descriptors = [
    'acidic',
    'all-natural',
    'airy',
    'aromatic',
    'bite-size',
    'bitter',
    'black',
    'bland',
    'bold',
    'bolognese',
    'brittle',
    'buttercream',
    'cajun',
    'candied',
    'chewy',
    'coarse',
    'cold',
    'condensed',
    'creamy',
    'creole',
    'crispy',
    'crunchy',
    'curdled',
    'cured',
    'dense',
    'diluted',
    'dried',
    'dry',
    'evaporated',
    'fatty',
    'fermented',
    'fine',
    'fresh',
    'fragrant',
    'garnish',
    'glazed',
    'granulated',
    'gourmet',
    'heavy',
    'hearty',
    'hot',
    'infused',
    'juicy',
    'kosher',
    'lean',
    'light',
    'limp',
    'liquid',
    'lowfat',
    'low-fat',
    'lukewarm',
    'lumpy',
    'medium',
    'mellow',
    'mild',
    'moist',
    'natural',
    'nutty',
    'odorless',
    'odor-less',
    'oily',
    'organic',
    'pasteurized',
    'pickled',
    'plump',
    'savory',
    'savoury',
    'rare',
    'raw',
    'rich',
    'ripe',
    'robust',
    'runny',
    'saturated',
    'savory',
    'savoury',
    'scented',
    'sea',
    'sharp',
    'skim',
    'smooth',
    'soft',
    'solid',
    'sour',
    'sparkling',
    'spicy',
    'stale',
    'stewed',
    'sticky',
    'stiff',
    'sweet',
    'tangy',
    'tart',
    'tender',
    'tepid',
    'thick',
    'tough'
    'unpasteurized',
    'un-pasteurized',
    'unripe',
    'un-ripe',
    'unscented',
    'un-scented',
    'virgin',
    'viscous',
    'warm',
    'watery',
    'wet',
    'whey',
    'whipped',
    'white',
    'wild',
    'wilted',
    'zest'
]

special_descriptors = [
    'whole wheat',
    'extra virgin'
]

preparations = [
    'barbecue',
    'barbeque',
    'bar-b-q',
    'bbq',
    'basted',
    'battered',
    'blackened',
    'blanched',
    'blended',
    'boiled',
    'braised',
    'brewed',
    'brined',
    'broiled',
    'browned',
    'carmelized',
    'charred',
    'chilled',
    'chopped',
    'creamed',
    'crumbled',
    'dehydrated',
    'dipped',
    'drenched',
    'drizzled',
    'escalloped',
    'folded',
    'freeze dried',
    'fried',
    'frosted',
    'frozen',
    'grated',
    'grilled',
    'ground',
    'hard-boiled',
    'iced',
    'julienned',
    'kneaded',
    'marinated',
    'mashed',
    'melted',
    'minced',
    'mixed',
    'pan-fried',
    'parboiled',
    'parched',
    'peppered',
    'poached',
    'powdered',
    'pulverized',
    'pureed',
    'reduced',
    'refrigerated',
    'roasted',
    'rolled',
    'salted',
    'saute',
    'scalded',
    'scrambled',
    'seared',
    'seasoned',
    'shredded',
    'sliced',
    'slivered',
    'smoked',
    'smothered',
    'soaked',
    'soft-boiled',
    'spritzed',
    'stewed',
    'steamed',
    'toasted',
    'wrapped'
]

# tools needed for prep (to get stuff in ingredients list)
prep_tools = {
        'basted': ['baster'],
        'blended': ['blender'],
        'julienned': ['cutting board', 'knife'],
        'mashed': ['potato masher'],
        'minced': ['cutting board', 'knife'],
        'chopped': ['cutting board', 'knife'],
        'grated': ['cheese grater'],
        'diced': ['cutting board', 'knife'],
        'peeled': ['peeler'],
        'sliced': ['cutting board', 'knife'],
        'slivered': ['cutting board', 'knife'],
        'halved': ['cutting board', 'knife'],
        'stirred': ['spoon'],
        'mixed': ['spoon'],
        'whisked': ['whisk'],
        'pulverized': ['food processor'],
        'pureed': ['food processor'],
        'tenderized': ['meat pounder']
    }

# tools needed for the tasks (to do the stuff in the directions)
task_tools = {
        'saute': ['pan'],
        'boil': ['pot'],
        'simmer': ['pot'],
        'grill': ['grill'],
        'char': ['grill'],
        'carmelize': ['pan'],
        'browned': ['oven'],
        'whip': ['whisk'],
        'combine': ['spoon', 'mixing bowl'],
        'puree': ['food processor'],
        'stir to combine': ['spoon', 'mixing bowl'],
        'blanche': ['pot', 'strainer', 'ice bath'],
        'braise': ['saucepan', 'oven'],
        'fried': ['pot', 'strainer'],
        'hard-boiled': ['pot'],
        'soft-boiled': ['pot'],
        'stew': ['large saucepot'],
        'sear': ['pan'],
        'scramble': ['whisk'],
        'reduced': ['sauce pot'],
        'pulverize': ['mortar and pestle'],
        'grind': ['mortar and pestle'],
        'pan-fry': ['pan'],
        'melt': ['bowl'],
        'mash': ['potato masher'],
        'poach': ['sauce pot']
    }